var localBibliography = {
  "SPARQL11": {
    title: "SPARQL 1.1 Query Language",
    href: "https://www.w3.org/TR/sparql11-query/",
    publisher: "W3C",
  },
  "SPARQLSD": {
    title: "SPARQL 1.1 Service Description",
    href: "https://www.w3.org/TR/sparql11-service-description/",
    publisher: "W3C",
  },
  "AS2": {
    title: "ActivityStreams 2.0 Vocabulary",
    href: "https://www.w3.org/TR/activitystreams-vocabulary/",
    rawDate: "2017-05-23",
    status: "REC",
    publisher: "W3C",
  },
  "LDP": {
    authors: ["Steve Speicher", "John Arwe", "Ashok Malhotra"],
    href: "https://www.w3.org/TR/ldp",
    title: "Linked Data Platform 1.0",
    rawDate: "2015-02-26",
    status: "REC",
    publisher: "W3C",
  },
  "SOLID-SPEC": {
    authors: ["Sarven Capadisli", "Tim Berners-Lee", "Kjetil Kjernsmo"],
    href: "https://solidproject.org/TR/protocol",
    title: "Solid Protocol",
    rawDate: "2024-05-12",
    status: "CG-DRAFT",
    publisher: "Solid Community Group",
  },
  "SHACL": {
    authors: ["Holger Knublauch", "Dimitris Kontokostas"],
    href: "https://www.w3.org/TR/shacl/",
    title: "Shapes Constraint Language (SHACL)",
    rawDate: "2017-07-20",
    status: "REC",
    publisher: "W3C",
  },
  "RDF11": {
    title: "RDF 1.1 Concepts and Abstract Syntax",
    href: "https://www.w3.org/TR/rdf11-concepts/",
    rawDate: "2014-02-25",
    publisher: "W3C",
  },
  "TURTLE": {
    title: "RDF 1.1 Turtle",
    authors: ["Eric Prud'hommeaux", "Gavin Carothers"],
    href: "https://www.w3.org/TR/turtle/",
    rawDate: "2014-02-25",
    status: "REC",
    publisher: "W3C",
  },
  "WEBID": {
    title: "WebID 1.0",
    authors: ["Andrei Sambra", "Stéphane Corlosquet"],
    href: "https://www.w3.org/2005/Incubator/webid/spec/identity/",
    rawDate: "2014-03-05",
    status: "ED",
    publisher: "W3C WebID Community Group",
  },
  "RFC9112": {
    title: "HTTP/1.1",
    authors: ["R. Fielding", "M. Nottingham", "J. Reschke"],
    href: "https://www.rfc-editor.org/rfc/rfc9112",
    rawDate: "2022-06",
    status: "Internet Standard",
    publisher: "IETF",
  },
  "RFC2119": {
    title: "Key words for use in RFCs to Indicate Requirement Levels",
    authors: ["S. Bradner"],
    href: "https://www.rfc-editor.org/rfc/rfc2119",
    rawDate: "1997-03",
    status: "Best Current Practice",
    publisher: "IETF",
  },
  "RFC3986": {
    title: "Uniform Resource Identifier (URI): Generic Syntax",
    authors: ["T. Berners-Lee", "R. Fielding", "L. Masinter"],
    href: "https://datatracker.ietf.org/doc/html/rfc3986",
    rawDate: "2005-01",
    status: "Internet Standard",
    publisher: "IETF",
  },
  "RFC8288": {
    title: "Web Linking",
    authors: ["M. Nottingham"],
    href: "https://httpwg.org/specs/rfc8288.html",
    rawDate: "2017-10",
    status: "Proposed Standard",
    publisher: "IETF",
  },
  "WAC": {
    title: "Solid Web Access Control",
    href: "https://solidproject.org/TR/wac",
    status: "CG-DRAFT",
    publisher: "Solid Community Group",
  }
};
